### ISSUE TITLE
If I change the main frequency of the H723 to 550MHz, what will it affect? I don't use an SD card or USB virtual serial port, but I will use the TerjeIO EEPROM plugin.

### ISSUE THREAD

**Issue by hanke-cnc** [dresco/STM32H7xx#22]
"I'm not very proficient with STM32, and I'm afraid this might lead to unnoticed errors."

**Comment by hanke-cnc** [comment]
"With the end of the pandemic and the fall in chip prices, I want to adopt H7 chips to provide people with stronger performance."
😎

**Comment by dresco** [comment]
Hi, changing the core frequency would affect all the peripheral clocks, which is why I've left the H723 boards at 480MHz so far - keeping them the same as the H743 parts for ease of development & testing.

It is on my list to create a 550MHz clock tree though, as I'm building a board around a H723 part also. (Hasn't been much of a priority, as 480MHz is basically fast enough already).

An additional problem with 550MHz is that it doesn't divide nicely for the 48MHz USB clock. However, the H7 parts have a clock recovery feature to trim the HSI48 clock from inbound USB packet timing, which should provide a reliable 48MHz clock source. I think this would probably be the way to go..

**Comment by hanke-cnc** [comment]
> Hi, changing the core frequency would affect all the peripheral clocks, which is why I've left the H723 boards at 480MHz so far - keeping them the same as the H743 parts for ease of development & testing.
> 
> It is on my list to create a 550MHz clock tree though, as I'm building a board around a H723 part also. (Hasn't been much of a priority, as 480MHz is basically fast enough already).
> 
> An additional problem with 550MHz is that it doesn't divide nicely for the 48MHz USB clock. However, the H7 parts have a clock recovery feature to trim the HSI48 clock from inbound USB packet timing, which should provide a reliable 48MHz clock source. I think this would probably be the way to go..

"Yes, 480MHz is already fast enough, but human nature is greedy. Okay, I'll temporarily run it at 480MHz."

**Comment by dresco** [comment]
> Yes, 480MHz is already fast enough, but human nature is greedy. Okay, I'll temporarily run it at 480MHz

Cool, will let you know when I've got a 550MHz clock setup tested..
