### ISSUE TITLE
Would this work with STM32G0B1VET6?

### ISSUE THREAD

**Issue by vaughnmonkey** [dresco/STM32H7xx#3]
I'm trying to get grblHAL to work with the [BTT Mantra M8P](https://biqu.equipment/products/manta-m4p-m8p?variant=39859521716322&sscid=a1k6_psftb&) board, it uses the STM32G0B1VET6. I'm an intermediately skilled programmer but completely new to firmware programming.

**Comment by dresco** [comment]
Afraid not, but the early commit history should give you an idea of whats involved in porting grblHAL to another ST processor family.

My approach was to start with an barebones STMCubeIDE project for the H743 processor, then import code from another grblHAL driver (the F7 driver in my case, as both are Cortex M7 parts). Then is a matter of working though the differences between the two in order to bring up a board - clock setup, peripherals etc.

I would suggest you'd be better off starting with a dev board (perhaps the [Nucleo](https://www.st.com/en/evaluation-tools/nucleo-g0b1re.html)), and then adding support for other boards. Is probably quite a challenge if you're not already familiar with STM32 HAL programming and the different families though..
